In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("../../data/rl_grounded_dataset_merged.csv")

In [4]:
data.head()

,user_query,hypothesis,metadata
0,What promising control directions could help l...,A quadrupedal robot can reduce fall damage in ...,"{""papers"": [{""id"": ""24badbe57bbe956ea38afd4b02..."
1,What research directions look most promising f...,A projection-based LiDAR semantic segmentation...,"{""papers"": [{""id"": ""bf872d5e3fcf46f44a1b9dd76e..."
2,What promising directions could improve short-...,In the endemic-epidemic framework for infectio...,"{""papers"": [{""id"": ""851aa1615fe70474d2ccf28fe7..."
3,What promising directions could make adversari...,A jointly trained conditional GAN that combine...,"{""papers"": [{""id"": ""4f0223b5db056b351fd736b4b6..."
4,What promising directions could help transform...,A transformer-based task-oriented dialogue sys...,"{""papers"": [{""id"": ""63169665bd592fb818678c4764..."

In [5]:
num_papers = []
for row in data.itertuples():
    metadata = eval(row.metadata)
    num_papers.append(len(metadata["papers"]))
data["num_papers"] = num_papers

In [9]:
data_filtered = data[(data["num_papers"] >= 3) & (data["num_papers"] <= 6)]

In [10]:
data_filtered

,user_query,hypothesis,metadata,num_papers
2,What promising directions could improve short-...,In the endemic-epidemic framework for infectio...,"{""papers"": [{""id"": ""851aa1615fe70474d2ccf28fe7...",6
5,What promising directions could help oriented-...,Discriminatively trained object detectors buil...,"{""papers"": [{""id"": ""d124f004fed2ee15860f624005...",6
6,What technical approaches look most promising ...,A stepwise workflow that combines NeuN-based n...,"{""papers"": [{""id"": ""fd89721f007f62d52cbc3ac329...",3
11,What promising directions could help greybox f...,A greybox fuzzer augmented with a large langua...,"{""papers"": [{""id"": ""470754e17de89081f63dde4719...",4
19,How might continuously collected home-based ph...,A consumer-grade wrist-worn wearable device su...,"{""papers"": [{""id"": ""eb354b58646061ad14e971b113...",3
...,...,...,...,...
978,What promising directions could make share-bas...,Higher-order AES masking schemes based on Mult...,"{""papers"": [{""id"": ""eacbec1a3acee23825ed3b520c...",3
990,What promising directions could improve cross-...,A cross-domain sentiment classifier becomes su...,"{""papers"": [{""id"": ""85031a4873fe4ddda4a0841b91...",5
994,What promising directions could reduce the ske...,Learning paired neural networks for sketches a...,"{""papers"": [{""id"": ""c43986083db2a17f10caf99cda...",4
995,What promising directions could improve the re...,Deep learning models that learn features direc...,"{""papers"": [{""id"": ""0f71c7b805d94e9d52bed7131e...",3
998,What promising directions exist for auditing a...,A black-box model’s indirect reliance on a fea...,"{""papers"": [{""id"": ""c0883f5930a232a9c1ad601c97...",6

In [13]:
interestin_rows = [
    59, 70, 98, 114, 125, 129, 151, 227
]
interestin_rows_data = data_filtered.loc[interestin_rows]
interestin_rows_data

,user_query,hypothesis,metadata,num_papers
59,What promising directions are there for assess...,Speaker-discriminative x-vector representation...,"{""papers"": [{""id"": ""57e41198769e171a6863c73709...",5
70,What promising directions could improve federa...,In federated learning with non-iid client data...,"{""papers"": [{""id"": ""08bd705920792314e3ef806c28...",4
98,What are promising directions for learning nod...,A multi-view network embedding model that join...,"{""papers"": [{""id"": ""36ee2c8bd605afd48035d15fdc...",6
114,What promising directions could improve explor...,Conversations with non-player characters (NPCs...,"{""papers"": [{""id"": ""8aed57b61457655e8354f1b68b...",3
125,What research directions could help model-base...,A model-based reinforcement learning agent tha...,"{""papers"": [{""id"": ""4be02694125b71876552900a53...",5
129,What training strategies could help language m...,"In neural language models, predicting coarser ...","{""papers"": [{""id"": ""320efa53dea3e8f836790682fb...",5
151,What promising directions could make attention...,Location-relative attention mechanisms that re...,"{""papers"": [{""id"": ""051238432e23a865981c95579d...",5
227,What promising directions are there for improv...,An adversarial domain adaptation model for Ara...,"{""papers"": [{""id"": ""d589392ab606a3d2861988ebcb...",6

In [14]:
interestin_rows_data.to_csv("../../data/interesting_rows.csv", index=False)

In [17]:
human_frendly_df = pd.DataFrame(columns=["user_query", "hypothesis", "paper_1", "paper_2", "paper_3", "paper_4", "paper_5", "paper_6"])
for index, row in interestin_rows_data.iterrows():
    metadata = eval(row.metadata)
    papers = metadata["papers"]
    papers = [paper["summary"] for paper in papers]
    papers = papers[:6] + [""] * (6 - len(papers))  # Pad with empty strings if less than 6 papers
    human_frendly_df.loc[len(human_frendly_df)] = [row.user_query, row.hypothesis] + papers

human_frendly_df.to_csv("../../data/interesting_rows_human_friendly.csv", index=False)